select * from customer
--Q1. What is the total revenue generated by male vs.female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
--Q2. Which customers used discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied= 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);


--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric), 2) as "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, 
ROUND(AVG(purchase_amount), 2)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
ROUND(AVG(purchase_amount), 2) as avg_spend,
SUM(purchase_amount) AS total_revenue,
COUNT(customer_id) AS total_customers
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied= 'Yes' THEN 1 ELSE 0 END) / COUNT (*), 2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
--Q7. Segment customers into New, Returning, previous purchases,and Loyal based on their total number of and show the count of each segment.
SELECT 
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;

--Q8. What are the top 3 most purchased products within each category?
SELECT category, item_purchased, total_purchases
FROM (
    SELECT category,
           item_purchased,
           COUNT(*) AS total_purchases,
           RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
) ranked
WHERE item_rank <= 3
ORDER BY category, total_purchases DESC;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS buyer_type,
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY 
        CASE WHEN previous_purchases > 5 THEN 'Repeat Buyer' ELSE 'Non-Repeat Buyer' END), 2) AS pct
FROM customer
GROUP BY buyer_type, subscription_status
ORDER BY buyer_type, subscription_status;

--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
order by total_revenue desc;
